# Generated by Django 4.0.6 on 2022-08-03 16:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.TextField(max_length=8)),
                ('nombre', models.TextField()),
                ('precio_compra', models.BooleanField()),
                ('precio_venta', models.BooleanField()),
                ('fecha_compra', models.DateField()),
                ('fecha_registro', models.DateField(default=datetime.datetime(2022, 8, 3, 11, 9, 31, 584323))),
                ('estado', models.TextField(default='A', max_length=1)),
            ],
        ),
    ]
