# Generated by Django 4.0.6 on 2022-08-03 16:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.TextField(max_length=8)),
                ('nombre', models.TextField()),
                ('horas', models.TextField()),
                ('creditos', models.TextField()),
                ('fecha_registro', models.DateField(default=datetime.datetime(2022, 8, 3, 11, 44, 55, 447870))),
                ('estado', models.TextField(default='A', max_length=1)),
            ],
        ),
        migrations.AlterField(
            model_name='producto',
            name='fecha_registro',
            field=models.DateField(default=datetime.datetime(2022, 8, 3, 11, 44, 55, 447870)),
        ),
        migrations.AlterField(
            model_name='producto',
            name='precio_compra',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='producto',
            name='precio_venta',
            field=models.IntegerField(),
        ),
    ]
